apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-debug
  labels:
    name: web-api
    instance: k8smaestro-web-api
    version: "1.0"
    component: weather-app-project
    part-of: backend
    managed-by: yaml 
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: web-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: pods-web-api
      labels:
        deployment: web-api
    spec:
      containers:
      - name: webapi
        image: k8smaestro/web-aqi:1.0
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/heallh"
            port: 80
            httpHeaders:
            - name: "Cookie"
              value: "session-id=x-readiness-probe"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 80
            httpHeaders:
            - name: "Cookie"
              value: "session-id=x-liveness-probe"
        resources:
          requests:
            cpu: 100m
            memory: 20Gi
          limits:
            cpu: 200m
            memory: 450Gi
---
apiVersion: v1
kind: Service
metadata:
  name: service-web-api-debugging
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    deployment: web-api