apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-requests-limits
spec:
  selector:
    matchLabels:
      name: web-api-requests-limits
  template:
    metadata:
      labels:
        name: web-api-requests-limits
    spec:
      containers:
      - name: webapi
        image: k8smaestro/web-api:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-web-api-requests-limits
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    name: web-api-requests-limits