apiVersion: v1
kind: Service
metadata:
  name: service-rollingupdate-frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    name: rollingupdate-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: service-rollingupdate-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    name: rollingupdate-backend