apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata: 
  name: compute-quota
  namespace: dev
spec:
  hard: 
    pods: "10" # maximum number of pods
    requests.cpu: "0.5"
    requests.memory: 1Gi # request: Sum of memory
    limits.cpu: "1"
    limits.memory: 2Gi # limit: Sum of memory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  namespace: dev
spec:
  selector:
    matchLabels:
      name: k8smaestro-webapp
  replicas: 3
  template:
    metadata:
      labels:
        name: k8smaestro-webapp
    spec:
      containers:
      - name: webapp-ctr
        image: k8smaestro/web-app:1.0
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
