apiVersion: v1
kind: Pod
metadata:
  name: webapp1
  labels:
    app: k8smaestro-webapp
spec:
  containers:
  - name: webapp1
    image: k8smaestro/web-app:1.0
---
apiVersion: v1
kind: Pod
metadata:
  name: webapp2
  labels:
    app: k8smaestro-webapp
spec:
  containers:
  - name: webapp2
    image: k8smaestro/web-app:2.0