apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-demo-deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: lb-demo
  template:
    metadata:
      labels:
        name: lb-demo
    spec:
      containers:
      - name: lb-ctr
        image: k8smaestro/host-detector:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lb-demo-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    name: lb-demo