apiVersion: v1
kind: Service
metadata:
  name: info-webapp-svc-v1
  labels:
    part-of: canary-demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: http # targetPort as name 
  selector: # Note here that we match both the app and the version
    name: info-webapp
    version: v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-deploy-v1
  labels:
    part-of: canary-demo
spec:
  replicas: 5
  selector: 
    matchLabels:
      name: info-webapp
      version: v1.0.0     
  template:
    metadata:
      labels:
        name: info-webapp
        version: v1.0.0
    spec:
      containers:
      - name: webapp-ctr
        image: k8smaestro/info
        ports:
        - name: http
          containerPort: 8080
        - name: probes
          containerPort: 8081
        env:
        - name: APP_VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probes
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probes
          periodSeconds: 5