apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo-nodejs
  labels:
    app: k8sdemo-nodejs
  namespace: k8sdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sdemo-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8sdemo-nodejs
    spec:
      containers:
      - image: k8smaestro/k8sdemo-nodejs:latest
        imagePullPolicy: Always
        name: k8sdemo-nodejs
        ports:
        - containerPort: 3000
          protocol: TCP
