apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  # automountServiceAccountToken: false
  containers:
  - name: curl
    image: curlimages/curl:7.77.0
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
