---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader-sa
  namespace: pod-reader
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-reader-pod
  namespace: pod-reader
spec:
  serviceAccountName: pod-reader-sa
  # automountServiceAccountToken: false
  containers:
  - name: curl
    image: curlimages/curl:7.77.0
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
