apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectapp-backend
spec:
  selector:
    matchLabels:
      name: projectapp-backend
  template:
    metadata:
      labels:
        name: projectapp-backend
    spec:
      containers:
      - name: backend
        image: k8smaestro/projectapp-backend:2.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-projectapp-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    name: projectapp-backend