apiVersion: v1
kind: Namespace
metadata:
  name: custom-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: custom-namespace-audit-excluded
---
apiVersion: v1
kind: Namespace
metadata:
  name: custom-namespace-audit-webhook-sync-excluded
--- 
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  match:
    - excludedNamespaces: ["kube-system", "gatekeeper-system", "custom-namespace"]
      processes: ["*"]
    - excludedNamespaces: ["custom-namespace-audit-excluded"]
      processes: ["audit"]
    - excludedNamespaces: ["custom-namespace-audit-webhook-sync-excluded"]
      processes: ["audit", "webhook", "sync"]