apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod-should-fail
  labels:
    run: webapp
spec:
  containers:
  - name: webapp
    image: k8smaestro/web-app:1.0
    ports:
      - containerPort: 80
    securityContext:
      privileged: true