apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  namespace: odoo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      volumes:
        - name: odoo
          persistentVolumeClaim:
            claimName: odoo-pvc
      containers:
        - name: odoo
          image: docker.io/bitnami/odoo:15
          ports:
            - containerPort: 8069
          volumeMounts:
            - mountPath: /bitnami/odoo
              name: odoo
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1"
          env:
            - name: ODOO_DATABASE_NAME
              value: "k8smaestro"
            - name: ODOO_DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: odoo-configmap
                  key: DB_USER
            - name: ODOO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-secret
                  key: DB_PASSWORD
            - name: ODOO_DATABASE_PORT_NUMBER
              value: "5432"
            - name: ODOO_DATABASE_HOST
              value: "postgresql.odoo.svc.cluster.local"
