apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-payment-deployment
spec:
  selector:
    matchLabels:
      app: busybox-payment
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox-payment
    spec:
      containers:
        - name: busybox-payment
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "MERCHANT_ID: $MERCHANT_ID"
              echo "PAYMENT_GATEWAY_API_KEY: $PAYMENT_GATEWAY_API_KEY"
          env:
            - name: MERCHANT_ID
              valueFrom:
                configMapKeyRef:
                  name: payment-configmap
                  key: MERCHANT_ID
            - name: PAYMENT_GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: payment-gateway-api-key
