apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
    - name: fast10g
      persistentVolumeClaim:
        claimName: ps-pvc
  containers:
    - name: main-ctr
      image: k8smaestro/web-app:1.0
      ports:
        - containerPort: 80
          name: http-server
      volumeMounts:
        - mountPath: /var/www/html
          name: fast10g